version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/de-supported-rhel8:latest'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system:
    - pkgconf-pkg-config [platform:rpm]
    - systemd-devel [platform:rpm]
    - gcc [platform:rpm]
    - python39-devel [platform:rpm]
  python_interpreter:
    package_system: "python39"

options:
  package_manager_path: /usr/bin/microdnf
